backend/project/src/main/java/com/lguplus/project/ProjectApplication.java
=> feat: commit_test

crawler/discountDataCrawler.py
Feature/be/discount data crawler
=> feat: discountDataCrawler

backend/project/src/main/java/com/lguplus/project/order/domain/Order.java
=> fix: Order Entity 변경

backend/project/src/main/java/com/lguplus/project/order/repository/OrderRepository.java
=> fix: OrderRepository 수정

backend/project/src/main/java/com/lguplus/project/order/domain/payload/OrderResponse.java
=> fix: OrderResponse 변경

backend/project/src/main/java/com/lguplus/project/benefitofplan/domain/BenefitOfPlan.java, backend/project/src/main/java/com/lguplus/project/device/domain/DeviceDetail.java, backend/project/src/main/java/com/lguplus/project/discount/domain/Discount.java, backend/project/src/main/java/com/lguplus/project/order/domain/Order.java
Add referencedColumnName parametr to @JoinColumn
Add FetchType.LAZY parameter to @JoinColumn
=> fix: entity_mapping

crawler/DiscountDataCrawler.py
=> fix: DiscountDataCrawler

backend/project/src/main/java/com/lguplus/project/order/domain/DiscountType.java, backend/project/src/main/java/com/lguplus/project/order/domain/JoinType.java, backend/project/src/main/java/com/lguplus/project/order/domain/Order.java
가입유형, 할인유형 enum class 추가 후 order 데이터 타입 변경
=> fix: enum class 추가, 데이터 타입 변경

backend/project/src/main/java/com/lguplus/project/order/domain/payload/OrderRequest.java, backend/project/src/main/java/com/lguplus/project/order/domain/payload/OrderResponse.java
feat: 주문 request dto 작성
fix: enum 타입으로 변경
=> feat: 주문 request dto 작성 및 enum 타입으로 변경

frontend/project/src/components/SearchBar.tsx, frontend/project/src/components/UplusButton.tsx, frontend/project/src/components/device/DeviceFilter.tsx, frontend/project/src/components/device/DeviceItem.tsx, frontend/project/src/components/device/DeviceSubFilter.tsx, frontend/project/src/index.scss, frontend/project/src/pages/HeaderPage.tsx, frontend/project/src/pages/device/DeviceListPage.tsx, frontend/project/src/theme.ts
상단 헤더 고정
상품 리스트 조회 레이아웃 작성
메인 필터 컴포넌트 작성
서브 필터 컴포넌트 작성
DeviceItem 컴포넌트 작성
=> feat: 상품 리스트 조회 페이지 레이아웃 작성

backend/project/src/main/java/com/lguplus/project/device/controller/DeviceController.java, backend/project/src/main/java/com/lguplus/project/device/domain/Device.java, backend/project/src/main/java/com/lguplus/project/device/domain/DeviceDetail.java, backend/project/src/main/java/com/lguplus/project/device/domain/payload/DeviceOptionsDetail.java, backend/project/src/main/java/com/lguplus/project/device/domain/payload/GetDeviceOptionsResponse.java, backend/project/src/main/java/com/lguplus/project/device/repository/DeviceRepository.java, backend/project/src/main/java/com/lguplus/project/device/service/DeviceServiceByDongWan.java
=> feat: 디바이스_옵션_상세_조회

backend/project/src/main/java/com/lguplus/project/device/controller/DeviceController.java, backend/project/src/main/java/com/lguplus/project/device/domain/Device.java, backend/project/src/main/java/com/lguplus/project/device/domain/payload/GetDevicePricesResponse.java, backend/project/src/main/java/com/lguplus/project/device/domain/payload/MonthlyCharge.java, backend/project/src/main/java/com/lguplus/project/device/service/DeviceServiceByDongWan.java, backend/project/src/main/java/com/lguplus/project/discount/domain/Discount.java, backend/project/src/main/java/com/lguplus/project/discount/repository/DiscountRepository.java, backend/project/src/main/java/com/lguplus/project/plan/domain/Plan.java
=> feat: 디바이스 가격 상세 조회

backend/project/build.gradle, backend/project/src/main/java/com/lguplus/project/config/SwaggerConfig.java, backend/project/src/main/java/com/lguplus/project/device/controller/DeviceController.java, backend/project/src/main/resources/application.yaml
Swagger  초기 설정
각 도메인 마다 SwaggerConfig 파일에
.apis(RequestHandlerSelectors.basePackage("com.lguplus.project.[도메인 패키지 이름].controller"))
ex) .apis(RequestHandlerSelectors.basePackage("com.lguplus.project.device.controller"))
추가하면 사용가능!
=> feat: Swagger Config

backend/project/src/main/java/com/lguplus/project/device/controller/DeviceController.java, backend/project/src/main/java/com/lguplus/project/device/service/DeviceServiceByDongWan.java
약정 요금 계산 로직 최적화
DI 방식 통일
테스트 컨트롤러 삭제
=> fix: 약정 요금 계산 로직 최적화

backend/project/src/main/java/com/lguplus/project/plan/controller/PlanController.java, backend/project/src/main/java/com/lguplus/project/plan/domain/Plan.java, backend/project/src/main/java/com/lguplus/project/plan/domain/payload/PlanResponse.java, backend/project/src/main/java/com/lguplus/project/plan/service/PlanService.java
PlanController, PlanService 작성
voice_call -> voiceCall 이름 변경
=> feat: 요금제 조회 기능 추가

backend/project/src/main/java/com/lguplus/project/device/controller/DeviceController.java
getDeviceOptions ApiResponse 수정
getDevicePrices ApiResponse 수정
=> chore: device_controller_swagger_api_response

backend/project/src/main/java/com/lguplus/project/order/exception/OrderNotFoundException.java, backend/project/src/main/java/com/lguplus/project/order/service/OrderService.java, backend/project/src/main/java/com/lguplus/project/plan/exception/PlanNotFoundException.java
feat: 주문 생성 exception 추가
feat: 주문 취소 기능 exception 추가 및 deleteOrder 메소드 로직 변경
=> feat: 주문 기능 exception 추가

backend/project/src/main/java/com/lguplus/project/order/controller/OrderContoller.java, backend/project/src/main/java/com/lguplus/project/order/repository/OrderRepository.java, backend/project/src/main/java/com/lguplus/project/order/service/OrderService.java
refactor: deleteOrder method 리팩토링
chore: swagger message 추가
=> refactor: deleteOrder method 리팩토링

frontend/project/src/App.tsx, frontend/project/src/components/device/DeviceCompareDialog.tsx, frontend/project/src/components/device/DeviceItem.tsx, frontend/project/src/components/device/DeviceSubFilter.tsx, frontend/project/src/components/device/PlanListDialog.tsx, frontend/project/src/pages/device/DeviceDetailPage.tsx
DeviceDetailPage 작성
PlanListDialog 레이아웃 작성
상품 상세정보 링크 연결
=> feat: 상품 상세 페이지 레이아웃 작성 

backend/project/src/main/java/com/lguplus/project/device/domain/DeviceDetail.java, backend/project/src/main/java/com/lguplus/project/device/exception/DeviceHaveNoStockException.java, backend/project/src/main/java/com/lguplus/project/device/repository/DeviceDetailRepository.java, backend/project/src/main/java/com/lguplus/project/global/handler/GlobalExceptionHandler.java, backend/project/src/main/java/com/lguplus/project/order/domain/Order.java, backend/project/src/main/java/com/lguplus/project/order/domain/payload/OrderRequest.java, backend/project/src/main/java/com/lguplus/project/order/domain/payload/OrderResponse.java, backend/project/src/main/java/com/lguplus/project/order/service/OrderService.java
- Order entity 색상 column 추가로 인한 변경
- 주문 생성 시 DeviceDetail 재고 반영
- 재고 없을 시 Exception 처리
- 존재하지 않는 색상 요청 시 Exception 처리
=> fix: 주문 생성 로직 변경

frontend/project/src/api/device.ts, frontend/project/src/api/order.ts, frontend/project/src/api/plan.ts, frontend/project/src/components/UplusButton.tsx, frontend/project/src/components/device/DeviceCompareDialog.tsx, frontend/project/src/components/device/DeviceCompareTab.tsx, frontend/project/src/components/device/DeviceFilter.tsx, frontend/project/src/components/device/DeviceItem.tsx, frontend/project/src/components/device/PlanListDialog.tsx, frontend/project/src/hooks/device/useDeviceList.tsx, frontend/project/src/hooks/order/useOrder.tsx, frontend/project/src/pages/HeaderPage.tsx, frontend/project/src/pages/device/DeviceDetailPage.tsx, frontend/project/src/pages/device/DeviceListPage.tsx
device, plan, order api, interface 작성
redux, react-query hooks 작성
styled props Type 일괄 수정
=> feat: device, plan, order api 연동

backend/project/src/main/java/com/lguplus/project/order/domain/Order.java, backend/project/src/main/java/com/lguplus/project/order/domain/payload/OrderResponse.java, backend/project/src/main/java/com/lguplus/project/order/service/OrderService.java
- order entity에 device_name, picPaths column 추가
- service 로직 변경
=> fix: order entity 변경으로 인한 수정

MSA/backend/project/order/src/main/java/com/uplus/order/service/KafkaConsumer.java
=> fix: consumeCreateOrderFail parameter data type 변경

MSA/backend/project/order/src/main/java/com/uplus/order/repository/OrderRepository.java, MSA/backend/project/order/src/main/java/com/uplus/order/service/KafkaConsumer.java, MSA/backend/project/order/src/main/java/com/uplus/order/service/OrderService.java, MSA/backend/project/order/src/main/resources/application.yaml
- application.yaml kafka 추가
- KafkaConsumer groupId 수정
- 주문 조회 로직 변경
- application.yaml server port 삭제
=> fix: application.yaml server port 삭제

frontend/project/src/api/device.ts, frontend/project/src/api/order.ts, frontend/project/src/components/device/DeviceCompareDialog.tsx, frontend/project/src/components/device/DeviceFilter.tsx, frontend/project/src/components/device/DeviceItem.tsx, frontend/project/src/components/device/DeviceSubFilter.tsx, frontend/project/src/components/device/PlanListDialog.tsx, frontend/project/src/data/staticData.ts, frontend/project/src/hooks/device/useDeviceOption.tsx, frontend/project/src/hooks/device/useDevicePrice.tsx, frontend/project/src/hooks/device/useFilter.tsx, frontend/project/src/lib/reducerUtils.ts, frontend/project/src/modules/device/actions.ts, frontend/project/src/modules/device/reducer.ts, frontend/project/src/modules/device/types.ts, frontend/project/src/pages/HeaderPage.tsx, frontend/project/src/pages/device/DeviceDetailPage.tsx, frontend/project/src/pages/device/DeviceListPage.tsx
useDeviceOption, useDevicePrice, useFilter Hooks 설계
setPlanFilter, setDeviceFilter, resetFilter Redux 설계
device 데이터 타입 변경
DeviceItem 데이터 연동
Device 필터, 정렬 구현
reducerUtils 수정 (로딩중 데이터 유지)
params, state 활용 필터 데이터 디테일로 전달
디테일 페이지 옵션 선택 구현 (기기 옵션, 요금제, 가입 유형)
디테일 페이지 주문하기 구현
공시지원금 할인 적용
요금 리스트 선택 범위 변경
요금 계산 마무리
=> feat: 상품 리스트, 디테일 페이지 설계

frontend/project/src/components/device/DeviceCompareDialog.tsx, frontend/project/src/components/device/DeviceCompareTab.tsx, frontend/project/src/components/device/DeviceItem.tsx, frontend/project/src/hooks/device/useCompareDeviceList.tsx, frontend/project/src/modules/device/actions.ts, frontend/project/src/modules/device/reducer.ts, frontend/project/src/modules/device/types.ts, frontend/project/src/pages/device/DeviceListPage.tsx
useCompareDeviceList hooks 작성
set/reset compareDeviceList Redux 설계
상품 비교하기 탭 데이터 연동
팝업 데이터 연동 (추후 수정 필요)
=> feat: 상품 비교하기 탭, 팝업 데이터 연동

MSA/backend/project/item/src/main/java/com/uplus/item/device/domain/payload/DevicePricesResponse.java, MSA/backend/project/item/src/main/java/com/uplus/item/device/service/DeviceServiceByDongWan.java, backend/project/src/main/java/com/lguplus/project/device/domain/payload/DevicePricesResponse.java, backend/project/src/main/java/com/lguplus/project/device/service/DeviceServiceByDongWan.java
Add InterestLIst In DevicePrice API
=> feat : Interest  List

MSA/backend/project/item/src/main/java/com/uplus/item/device/service/DeviceServiceByDongWan.java, backend/project/src/main/java/com/lguplus/project/device/service/DeviceServiceByDongWan.java
=> feat: reafctor makeInterestList

frontend/project/src/pages/search/SearchPage.tsx
=> fix: 비교하기 기능 수정

frontend/project/src/api/search.ts, frontend/project/src/components/SearchBar.tsx, frontend/project/src/components/device/DeviceCompareDialog.tsx, frontend/project/src/pages/HeaderPage.tsx, frontend/project/src/pages/device/DeviceListPage.tsx
autoCompletion 적용
요금 그래프 단위 설정
비교하기 탭 기본값 닫힘 설정
=> feat: Search AutoCompletion API 적용

frontend/project/src/hooks/cart/useCookieCart.tsx, frontend/project/src/index.tsx, frontend/project/src/pages/HeaderPage.tsx
=> feat: 장바구니 쿠키 Hook 설계

frontend/project/src/api/device.ts, frontend/project/src/api/order.ts, frontend/project/src/api/plan.ts, frontend/project/src/api/search.ts, frontend/project/src/lib/customApi.ts
=> feat: MSA API 연동

frontend/project/src/components/cart/CartItem.tsx, frontend/project/src/components/device/DeviceCompareDialog.tsx, frontend/project/src/components/device/DeviceItem.tsx, frontend/project/src/hooks/cart/useCookieCart.tsx, frontend/project/src/index.scss, frontend/project/src/pages/cart/CartPage.tsx, frontend/project/src/pages/device/DeviceDetailPage.tsx, frontend/project/src/pages/device/DeviceListPage.tsx
'상품 목록, 비교하기, 상세 정보'에서 장바구니 추가 활성화
장바구니 확인 Alert 적용
장바구니 삭제 후 쿠키 동기화 설정
=> feat: 장바구니 추가 구현
